## Домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Python_Introduction_2022</b>» в github 

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


In [1]:
import numpy as np

1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [2]:
a, b, c = -1.3, 2.5, 64
array_1 = np.linspace(a, b, c)
array_1

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [3]:
n = int(input())
array_2 = [i%3+1 for i in range(3*n)]
array_2

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

3.	Создайте массив первых 10 нечетных целых чисел.

In [4]:
array_3 = np.linspace(1, 19, 10, dtype="int32")
array_3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [5]:
array_4 = np.zeros((10, 10), dtype = "int32")
print(array_4)

for i in range(len(array_4)):
    for j in range(len(array_4)):
        if i == 0 or j == 0 or i == len(array_4) - 1 or j == len(array_4) - 1:
            array_4[i][j] = 1

print(array_4)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [6]:
array_5 = np.fromfunction(lambda i, j: (i - j)%2, (6, 6))
array_5

array([[0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [7]:
#n = int(input())
n = 8
array_6 = np.fromfunction(lambda i, j: i + j, (n, n))
array_6

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14.]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [8]:
import numpy as np

array_6 = np.fromfunction(lambda i, j: i + j, (8, 8), dtype="int32")

array_7_1 = np.matrix('1 2 3 4 5 6 7 8', dtype = 'int32')
print(array_7_1)

vector_7 = np.matrix('1;2;3;4;5;6;7;8', dtype="int32")
print(vector_7)

print("вектор на вектор -\n", np.dot(array_7_1, vector_7))
print("матрицу на вектор ->\n", np.dot(array_6, vector_7))
print("матрицу на матрицу ->\n", np.dot(array_6, array_6))

[[1 2 3 4 5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
вектор на вектор -
 [[204]]
матрицу на вектор ->
 [[168]
 [204]
 [240]
 [276]
 [312]
 [348]
 [384]
 [420]]
матрицу на матрицу ->
 [[140 168 196 224 252 280 308 336]
 [168 204 240 276 312 348 384 420]
 [196 240 284 328 372 416 460 504]
 [224 276 328 380 432 484 536 588]
 [252 312 372 432 492 552 612 672]
 [280 348 416 484 552 620 688 756]
 [308 384 460 536 612 688 764 840]
 [336 420 504 588 672 756 840 924]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [9]:
sin_8 = [np.sin(i) for i in np.arange(0, 1.05, 0.05)]
print(sin_8)

cos_8 = [np.cos(i) for i in np.arange(0, 1.05, 0.05)]
print(cos_8)

sin_8 = str(sin_8) + str(cos_8)
print(sin_8)

[0.0, 0.04997916927067833, 0.09983341664682815, 0.14943813247359924, 0.19866933079506122, 0.24740395925452294, 0.2955202066613396, 0.3428978074554514, 0.3894183423086505, 0.43496553411123023, 0.479425538604203, 0.5226872289306592, 0.5646424733950355, 0.6051864057360395, 0.6442176872376911, 0.6816387600233341, 0.7173560908995228, 0.7512804051402927, 0.7833269096274834, 0.8134155047893737, 0.8414709848078965]
[1.0, 0.9987502603949663, 0.9950041652780258, 0.9887710779360422, 0.9800665778412416, 0.9689124217106447, 0.955336489125606, 0.9393727128473789, 0.9210609940028851, 0.9004471023526769, 0.8775825618903728, 0.8525245220595057, 0.8253356149096782, 0.7960837985490559, 0.7648421872844884, 0.7316888688738209, 0.6967067093471654, 0.6599831458849821, 0.6216099682706644, 0.5816830894638835, 0.5403023058681398]
[0.0, 0.04997916927067833, 0.09983341664682815, 0.14943813247359924, 0.19866933079506122, 0.24740395925452294, 0.2955202066613396, 0.3428978074554514, 0.3894183423086505, 0.43496553411

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [10]:
matrix_9 = np.random.rand(3, 5) * 4 - 1
matrix_9

array([[-0.73237818,  1.88693409, -0.37028795,  0.77077035,  2.60372477],
       [ 1.49781806,  1.45059579,  2.68667467,  1.38558981,  0.54013335],
       [-0.01959373,  0.61337905,  1.88543395,  2.6159227 ,  2.87222955]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [11]:
A = np.random.rand(5, 5) * 10

sum = A.sum()
sum_low = A.sum(axis=1)
sum_cow = A.sum(axis=0)
average = A.mean()
disp = A.var()
stand = A.std()

print("{}\n {}\n {}\n {}\n {}\n {}\n {}\n".format(A, sum, sum_low, sum_low, average, disp, stand))

[[4.79450785 9.03150127 7.16291307 3.9023948  8.28626695]
 [2.24608547 5.38280111 0.94697868 4.44388912 8.42391045]
 [0.67062347 6.37477535 7.41377533 1.05677478 7.11446918]
 [5.09137189 3.83770836 1.09438764 6.36386086 8.58177651]
 [6.12978294 7.53030441 6.60489069 4.17831687 5.60578919]]
 132.26985622147566
 [33.17758394 21.44366482 22.63041811 24.96910525 30.04908409]
 [33.17758394 21.44366482 22.63041811 24.96910525 30.04908409]
 5.290794248859027
 6.24529896087876
 2.4990596153110793



11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [12]:
A = (A - average) / stand
A

array([[-0.19858926,  1.49684585,  0.74912931, -0.55556876,  1.19863995],
       [-1.2183418 ,  0.03681659, -1.73818005, -0.33888953,  1.25371807],
       [-1.84876373,  0.4337556 ,  0.84951198, -1.69424508,  0.72974447],
       [-0.07979896, -0.58145307, -1.67919428,  0.42938816,  1.31688826],
       [ 0.33572176,  0.89614115,  0.52583637, -0.4451584 ,  0.12604539]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [13]:
A[A[:, 2].argsort()]

array([[-1.2183418 ,  0.03681659, -1.73818005, -0.33888953,  1.25371807],
       [-0.07979896, -0.58145307, -1.67919428,  0.42938816,  1.31688826],
       [ 0.33572176,  0.89614115,  0.52583637, -0.4451584 ,  0.12604539],
       [-0.19858926,  1.49684585,  0.74912931, -0.55556876,  1.19863995],
       [-1.84876373,  0.4337556 ,  0.84951198, -1.69424508,  0.72974447]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [14]:
B = np.dot(np.transpose(A), A)
C = np.dot(A, np.transpose(A))

print(B)
print(C)

[[ 5.06079873 -0.79677089  0.70891411  3.47175803 -3.1773894 ]
 [-0.79677089  3.57120353  2.8734141  -2.22755966  1.50411336]
 [ 0.70891411  2.8734141   7.40033254 -2.22152994 -2.80635672]
 [ 3.47175803 -2.22755966 -2.22152994  3.67650935 -1.81781875]
 [-3.1773894   1.50411336 -2.80635672 -1.81781875  5.29115585]]
[[ 4.58657432  0.68596973  3.46877473 -0.77251183  2.06703301]
 [ 0.68596973  6.1936372   2.2808465   4.50004874 -0.98114438]
 [ 3.46877473  2.2808465   7.73073524 -1.29767161  1.06092868]
 [-0.77251183  4.50004874 -1.29767161  5.08271785 -1.45599375]
 [ 2.06703301 -0.98114438  1.06092868 -1.45599375  1.40633539]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [15]:
print(np.trace(B), np.trace(C))

25.0 25.000000000000004


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [18]:
print(np.linalg.det(A), np.linalg.det(B), np.linalg.det(C))
print(np.linalg.matrix_rank(A), np.linalg.matrix_rank(B), np.linalg.matrix_rank(C))
print(np.linalg.eig(A), np.linalg.eig(B), np.linalg.eig(C))

3.0423717968471435 9.256026150250944 9.25602615025101
5 5 5
(array([ 1.8023741 +0.j        , -0.83853521+0.49684892j,
       -0.83853521-0.49684892j,  0.55893459+1.21012938j,
        0.55893459-1.21012938j]), array([[ 0.03940117+0.j        , -0.39736268-0.10534803j,
        -0.39736268+0.10534803j,  0.55315999+0.j        ,
         0.55315999-0.j        ],
       [-0.5300544 +0.j        ,  0.49421674-0.14472212j,
         0.49421674+0.14472212j, -0.33991507+0.36993685j,
        -0.33991507-0.36993685j],
       [ 0.66378666+0.j        ,  0.22105968-0.06078734j,
         0.22105968+0.06078734j,  0.3291553 +0.12121417j,
         0.3291553 -0.12121417j],
       [-0.52135205+0.j        ,  0.68394781+0.j        ,
         0.68394781-0.j        , -0.37832984-0.13827805j,
        -0.37832984+0.13827805j],
       [ 0.07119825+0.j        , -0.18250337+0.11025171j,
        -0.18250337-0.11025171j,  0.39299893-0.04335859j,
         0.39299893+0.04335859j]])) (array([11.26922394, 10.43612685,  2.89

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [17]:
from numpy import vectorize


np.random.seed(1032212274)
np.random.randint(10)

def f(x):
    return np.cos(np.log(x))/x

a = 1
b = np.e

d_x_1 = 0.1
d_x_2 = 0.01
d_x_3 = 0.001
d_x_4 = 0.0001
d_x_5 = 0.00001
d_x_6 = 0.000001

vector = np.vectorize(f)

# a)	Прямоугольников ********************************

I_1_1 = vector(np.arange(a, b + d_x_1, d_x_1)).sum() * d_x_1
I_1_2 = vector(np.arange(a, b + d_x_2, d_x_2)).sum() * d_x_2
I_1_3 = vector(np.arange(a, b + d_x_3, d_x_3)).sum() * d_x_3
I_1_4 = vector(np.arange(a, b + d_x_4, d_x_4)).sum() * d_x_4
I_1_5 = vector(np.arange(a, b + d_x_5, d_x_5)).sum() * d_x_5
I_1_6 = vector(np.arange(a, b + d_x_6, d_x_6)).sum() * d_x_6


print("\n1-й интеграл, заначения: ")
print(I_1_1)
print(I_1_2)
print(I_1_3)
print(I_1_4)
print(I_1_5)
print(I_1_6)

# b)	Трапеций ***************************************

I_2_1 = vector(np.arange(a + d_x_1, b, d_x_1)).sum() * d_x_1 + d_x_1 * (vector(a) + vector(b)) / 2
I_2_2 = vector(np.arange(a + d_x_2, b, d_x_2)).sum() * d_x_2 + d_x_2 * (vector(a) + vector(b)) / 2
I_2_3 = vector(np.arange(a + d_x_3, b, d_x_3)).sum() * d_x_3 + d_x_3 * (vector(a) + vector(b)) / 2
I_2_4 = vector(np.arange(a + d_x_4, b, d_x_4)).sum() * d_x_4 + d_x_4 * (vector(a) + vector(b)) / 2
I_2_5 = vector(np.arange(a + d_x_5, b, d_x_5)).sum() * d_x_5 + d_x_5 * (vector(a) + vector(b)) / 2
I_2_6 = vector(np.arange(a + d_x_6, b, d_x_6)).sum() * d_x_6 + d_x_6 * (vector(a) + vector(b)) / 2

print("\n2-й интеграл, заначения: ")
print(I_2_1)
print(I_2_2)
print(I_2_3)
print(I_2_4)
print(I_2_5)
print(I_2_6)

# c)	По правилу Симпсона ****************************

I_3_1 = vector(np.arange(a + d_x_1, b, d_x_1 * 2)).sum() * d_x_1 * 2 / 3 + vector(np.arange(a + d_x_1  * 2, b, d_x_1 * 2)).sum() * d_x_1 * 4 / 3 + d_x_1 * (vector(a) + vector(b)) / 3
I_3_2 = vector(np.arange(a + d_x_2, b, d_x_2 * 2)).sum() * d_x_2 * 2 / 3 + vector(np.arange(a + d_x_2  * 2, b, d_x_2 * 2)).sum() * d_x_2 * 4 / 3 + d_x_2 * (vector(a) + vector(b)) / 3
I_3_3 = vector(np.arange(a + d_x_3, b, d_x_3 * 2)).sum() * d_x_3 * 2 / 3 + vector(np.arange(a + d_x_3  * 2, b, d_x_3 * 2)).sum() * d_x_3 * 4 / 3 + d_x_3 * (vector(a) + vector(b)) / 3
I_3_4 = vector(np.arange(a + d_x_4, b, d_x_4 * 2)).sum() * d_x_4 * 2 / 3 + vector(np.arange(a + d_x_4  * 2, b, d_x_4 * 2)).sum() * d_x_4 * 4 / 3 + d_x_4 * (vector(a) + vector(b)) / 3
I_3_5 = vector(np.arange(a + d_x_5, b, d_x_5 * 2)).sum() * d_x_5 * 2 / 3 + vector(np.arange(a + d_x_5  * 2, b, d_x_5 * 2)).sum() * d_x_5 * 4 / 3 + d_x_5 * (vector(a) + vector(b)) / 3
I_3_6 = vector(np.arange(a + d_x_6, b, d_x_6 * 2)).sum() * d_x_6 * 2 / 3 + vector(np.arange(a + d_x_6  * 2, b, d_x_6 * 2)).sum() * d_x_6 * 4 / 3 + d_x_6 * (vector(a) + vector(b)) / 3

print("\n3-й интеграл, заначения: ")
print(I_3_1)
print(I_3_2)
print(I_3_3)
print(I_3_4)
print(I_3_5)
print(I_3_6)

print("\nСравним:")
print(I_1_6)
print(I_2_6)
print(I_3_6)


1-й интеграл, заначения: 
0.9169895052658836
0.8478112255107567
0.8422130684396536
0.841534535476704
0.8414786028534754
0.8414716183286571

2-й интеграл, заначения: 
0.8585297721780634
0.8418206057349352
0.8416138196451437
0.8414745975109968
0.8414726090382045
0.8414710189456337

3-й интеграл, заначения: 
0.8195048423509028
0.8378320310008588
0.8412805628427381
0.8414412651101951
0.8414692757177664
0.8414706193014995

Сравним:
0.8414716183286571
0.8414710189456337
0.8414706193014995
