## Домашнее задание - Библиотека numpy

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Python_Introduction_2022</b>» в github 

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


In [342]:
import numpy as np

1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [343]:
a, b, c = -1.3, 2.5, 64
array_1 = np.linspace(a, b, c)
array_1

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [344]:
n = int(input())
array_2 = [i%3+1 for i in range(3*n)]
array_2

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

3.	Создайте массив первых 10 нечетных целых чисел.

In [345]:
array_3 = np.linspace(1, 19, 10)
array_3

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [346]:
array_4 = np.zeros((10, 10), dtype = "int32")
print(array_4)

for i in range(len(array_4)):
    for j in range(len(array_4)):
        if i == 0 or j == 0 or i == len(array_4) - 1 or j == len(array_4) - 1:
            array_4[i][j] = 1

print(array_4)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [347]:
array_5 = np.fromfunction(lambda i, j: (i - j)%2, (6, 6))
array_5

array([[0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0.]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [348]:
#n = int(input())
n = 8
array_6 = np.fromfunction(lambda i, j: i + j, (n, n))
array_6

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [ 4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [ 5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 6.,  7.,  8.,  9., 10., 11., 12., 13.],
       [ 7.,  8.,  9., 10., 11., 12., 13., 14.]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [349]:
import numpy as np

array_6 = np.fromfunction(lambda i, j: i + j, (8, 8), dtype="int32")

array_7_1 = np.matrix('1 2 3 4 5 6 7 8', dtype = 'int32')
print(array_7_1)

vector_7 = np.matrix('1;2;3;4;5;6;7;8', dtype="int32")
print(vector_7)

print("вектор на вектор -\n", np.dot(array_7_1, vector_7))
print("матрицу на вектор ->\n", np.dot(array_6, vector_7))
print("матрицу на матрицу ->\n", np.dot(array_6, array_6))

[[1 2 3 4 5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
вектор на вектор -
 [[204]]
матрицу на вектор ->
 [[168]
 [204]
 [240]
 [276]
 [312]
 [348]
 [384]
 [420]]
матрицу на матрицу ->
 [[140 168 196 224 252 280 308 336]
 [168 204 240 276 312 348 384 420]
 [196 240 284 328 372 416 460 504]
 [224 276 328 380 432 484 536 588]
 [252 312 372 432 492 552 612 672]
 [280 348 416 484 552 620 688 756]
 [308 384 460 536 612 688 764 840]
 [336 420 504 588 672 756 840 924]]


8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [350]:
sin_8 = [np.sin(i) for i in np.arange(0, 1.05, 0.05)]
print(sin_8)

cos_8 = [np.cos(i) for i in np.arange(0, 1.05, 0.05)]
print(cos_8)

sin_8 = str(sin_8) + str(cos_8)
print(sin_8)

[0.0, 0.04997916927067833, 0.09983341664682815, 0.14943813247359924, 0.19866933079506122, 0.24740395925452294, 0.2955202066613396, 0.3428978074554514, 0.3894183423086505, 0.43496553411123023, 0.479425538604203, 0.5226872289306592, 0.5646424733950355, 0.6051864057360395, 0.6442176872376911, 0.6816387600233341, 0.7173560908995228, 0.7512804051402927, 0.7833269096274834, 0.8134155047893737, 0.8414709848078965]
[1.0, 0.9987502603949663, 0.9950041652780258, 0.9887710779360422, 0.9800665778412416, 0.9689124217106447, 0.955336489125606, 0.9393727128473789, 0.9210609940028851, 0.9004471023526769, 0.8775825618903728, 0.8525245220595057, 0.8253356149096782, 0.7960837985490559, 0.7648421872844884, 0.7316888688738209, 0.6967067093471654, 0.6599831458849821, 0.6216099682706644, 0.5816830894638835, 0.5403023058681398]
[0.0, 0.04997916927067833, 0.09983341664682815, 0.14943813247359924, 0.19866933079506122, 0.24740395925452294, 0.2955202066613396, 0.3428978074554514, 0.3894183423086505, 0.43496553411

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [351]:
matrix_9 = np.random.rand(3, 5) * 4 - 1
matrix_9

array([[-0.60345686,  2.88938446,  1.25704054,  2.72553802,  1.88801896],
       [ 0.36357205,  1.64692153,  0.55014738,  1.47677929, -0.44189943],
       [ 1.65221336,  0.57832043, -0.47896139, -0.73939393,  2.19569824]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [352]:
A = np.random.rand(5, 5) * 10

sum = A.sum()
sum_low = A.sum(axis=1)
sum_cow = A.sum(axis=0)
average = A.mean()
disp = A.var()
stand = A.std()

print("{}\n {}\n {}\n {}\n {}\n {}\n {}\n".format(A, sum, sum_low, sum_low, average, disp, stand))

[[7.70351828 7.91884995 6.20700862 5.73802014 9.38986963]
 [1.25687975 0.6986753  5.91928643 2.65819015 3.75975637]
 [1.20457948 8.99413179 6.01643168 8.09584297 6.99104267]
 [8.69751197 4.57540273 9.10982556 9.29090852 6.51737686]
 [9.48641672 8.5205355  0.99834832 9.42656167 9.19752622]]
 158.37249731210684
 [36.95726663 14.29278801 31.30202859 38.19102564 37.62938844]
 [36.95726663 14.29278801 31.30202859 38.19102564 37.62938844]
 6.334899892484274
 8.603110488650334
 2.9331059456914157



11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [353]:
A = (A - average) / stand
A

array([[ 0.46661062,  0.54002484, -0.04360268, -0.20349751,  1.04154769],
       [-1.73127744, -1.92158916, -0.14169739, -1.25352095, -0.8779579 ],
       [-1.74910846,  0.90662661, -0.10857712,  0.60036804,  0.22370238],
       [ 0.80549838, -0.59987508,  0.94607072,  1.00780834,  0.06221288],
       [ 1.07446403,  0.74516081, -1.81941998,  1.05405732,  0.97597099]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [354]:
# A = np.sort(A, axis=0)
# print(A)

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [355]:
B = np.dot(np.transpose(A), A)
C = np.dot(A, np.transpose(A))

print(B)
print(C)

[[ 8.07772801  2.3104471  -0.7779577   2.96946426  2.71346429]
 [ 2.3104471   5.72121828 -1.77298599  3.0240513   3.14228591]
 [-0.7779577  -1.77298599  4.23910722 -0.84300753 -1.66214223]
 [ 2.96946426  3.0240513  -0.84300753  4.09988225  2.11431804]
 [ 2.71346429  3.14228591 -1.66214223  2.11431804  2.86206424]]
[[ 1.63748633 -2.49870656 -0.21099415 -0.12963336  1.78511556]
 [-2.49870656  9.05202944  0.35243805 -1.69381262 -5.21242557]
 [-0.21099415  0.35243805  4.30362573 -1.43651528 -0.15507474]
 [-0.12963336 -1.69381262 -1.43651528  2.92327564 -0.17981863]
 [ 1.78511556 -5.21242557 -0.15507474 -0.17981863  7.08358286]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [356]:
print(np.trace(B, offset = 0,axis1=0, axis2 = 1), np.trace(C, offset = 0,axis1=0, axis2 = 1))

24.999999999999993 25.0


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [357]:
print(np.linalg.det(A), np.linalg.det(B), np.linalg.det(C))
print(np.linalg.matrix_rank(A), np.linalg.matrix_rank(B), np.linalg.matrix_rank(C))
# print(np.linalg.__spec__(A), np.linalg.__spec__(B), np.linalg.__spec__(C))

-14.9245037410261 222.7408119159017 222.7408119159023
5 5 5


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>